


from PyQt5 import QtCore, QtGui, QtWidgets
import Model


class Ui_Convertor(object):
    def setupUi(self, Convertor):
        Convertor.setObjectName("Convertor")
        Convertor.resize(735, 568)
        Convertor.setMaximumSize(QtCore.QSize(779, 16777215))
        Convertor.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/76-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Convertor.setWindowIcon(icon)
        Convertor.setStyleSheet("QLabel {\n"
"\n"
"color:black;\n"
"}")
        self.label = QtWidgets.QLabel(Convertor)
        self.label.setGeometry(QtCore.QRect(-60, -10, 861, 641))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Convertor)
        self.frame.setGeometry(QtCore.QRect(30, 20, 731, 541))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(400, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.ent_amount = QtWidgets.QLineEdit(self.frame)
        self.ent_amount.setGeometry(QtCore.QRect(140, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ent_amount.setFont(font)
        self.ent_amount.setStyleSheet("")
        self.ent_amount.setObjectName("ent_amount")
        self.ent_final = QtWidgets.QLineEdit(self.frame)
        self.ent_final.setGeometry(QtCore.QRect(460, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ent_final.setFont(font)
        self.ent_final.setStyleSheet("")
        self.ent_final.setReadOnly(True)
        self.ent_final.setObjectName("ent_final")
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setGeometry(QtCore.QRect(0, -10, 731, 51))
        self.frame1.setStyleSheet("")
        self.frame1.setObjectName("frame1")
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:black;\n"
"background-color: transparent;\n"
"")
        self.label_2.setObjectName("label_2")
        self.btn_convert = QtWidgets.QPushButton(self.frame)
        self.btn_convert.setGeometry(QtCore.QRect(550, 210, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_convert.setFont(font)
        self.btn_convert.setStyleSheet("")
        self.btn_convert.setObjectName("btn_convert")
        self.lbl_connect = QtWidgets.QLabel(self.frame)
        self.lbl_connect.setGeometry(QtCore.QRect(30, 50, 90, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_connect.setFont(font)
        self.lbl_connect.setStyleSheet("color: black;")
        self.lbl_connect.setObjectName("lbl_connect")
        self.ent_name = QtWidgets.QLineEdit(self.frame)
        self.ent_name.setGeometry(QtCore.QRect(140, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ent_name.setFont(font)
        self.ent_name.setStyleSheet("")
        self.ent_name.setObjectName("ent_name")
        self.tbn_search = QtWidgets.QPushButton(self.frame)
        self.tbn_search.setGeometry(QtCore.QRect(340, 210, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbn_search.setFont(font)
        self.tbn_search.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/flaticon_search-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbn_search.setIcon(icon1)
        self.tbn_search.setObjectName("tbn_search")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(50, 280, 591, 211))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(33)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(400, 150, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.btn_refresh = QtWidgets.QPushButton(self.frame)
        self.btn_refresh.setGeometry(QtCore.QRect(600, 40, 41, 41))
        self.btn_refresh.setStyleSheet("QPushButton{\n"
"\n"
"background-color:transparent;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton  hover {\n"
"\n"
"\n"
"background-color:rgb(235, 255, 237);\n"
"}")
        self.btn_refresh.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/76-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh.setIcon(icon2)
        self.btn_refresh.setIconSize(QtCore.QSize(50, 50))
        self.btn_refresh.setObjectName("btn_refresh")
        self.label_8 = QtWidgets.QLabel(Convertor)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 51, 111))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setStyleSheet("color: rgb(0, 255, 72);\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(Convertor)
        self.label_11.setGeometry(QtCore.QRect(90, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.tbn_search.clicked.connect(lambda : self.search())
        self.btn_refresh.clicked.connect(lambda : self.check_connection())
        self.btn_convert.clicked.connect(lambda : self.convert())

        self.retranslateUi(Convertor)
        QtCore.QMetaObject.connectSlotsByName(Convertor)
    
    def check_connection(self):
        self.ent_final.setText("")
        self.ent_amount.setText("")
        self.ent_name.setText("")
        if  Model.Connection.check() is True:
            self.btn_convert.setEnabled(True)
            self.lbl_connect.setStyleSheet("color:green;")
            self.lbl_connect.setText("Connected")
            self.label_8.setStyleSheet("color:green;")
        else:
            self.btn_convert.setEnabled(False)
            self.lbl_connect.setStyleSheet("color:red;")
            self.lbl_connect.setText("Disconnected")
            self.label_8.setStyleSheet("color:red;")

    def search(self):
        val = self.ent_name.text()
        if val == "":
            self.ent_name.setStyleSheet("background-color:#eee;")
        else:
            self.ent_name.setStyleSheet("background-color: rgb(255, 255, 255);")
            ob = Model.Database()
            data =  ob.search_codes(val)
            self.tableWidget.setRowCount(0)
            
            for row, form in enumerate(data):
                self.tableWidget.insertRow(row)
                for column, item in enumerate(form):
                    self.tableWidget.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))

    def convert(self):
        convert1 = self.comboBox.currentText()
        final = self.comboBox_2.currentText()
        if final == convert1:
            self.ent_final.setText(self.ent_amount.text())
            return
        a = Model.API()
        rate = a.convert_currecy(convert1,final,self.ent_amount.text())
        self.ent_final.setText(str(rate))

    
    def fill_all(self):
        a = Model.Database()
        data =  a.get_codes()

        code = sorted({i[1] for i in data})
        for i in code:
            self.comboBox_2.addItem(i)
            self.comboBox.addItem(i)


        for row, form in enumerate(data):
            self.tableWidget.insertRow(row)
            for column, item in enumerate(form):
                self.tableWidget.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))

    def retranslateUi(self, Convertor):
        _translate = QtCore.QCoreApplication.translate
        Convertor.setWindowTitle(_translate("Convertor", "Dialog"))
        self.label_3.setText(_translate("Convertor", "From:"))
        self.label_4.setText(_translate("Convertor", "To:"))
        self.label_2.setText(_translate("Convertor", "Currency Converter"))
        self.btn_convert.setText(_translate("Convertor", "Convert"))
        self.lbl_connect.setToolTip(_translate("Convertor", "<html><head/><body><p>Connection Status</p></body></html>"))
        self.lbl_connect.setText(_translate("Convertor", "Connected"))
        self.tbn_search.setText(_translate("Convertor", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Convertor", "S.No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Convertor", "Currency Code"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Convertor", "Country Name"))
        self.label_6.setText(_translate("Convertor", "Amount:"))
        self.label_10.setText(_translate("Convertor", "Final:"))
        self.btn_refresh.setToolTip(_translate("Convertor", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Refresh Connection</span></p></body></html>"))
        self.label_8.setText(_translate("Convertor", "."))
        self.label_11.setText(_translate("Convertor", "Name:"))
        self.fill_all()
        self.check_connection()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Convertor = QtWidgets.QDialog()
    ui = Ui_Convertor()
    ui.setupUi(Convertor)
    Convertor.show()

    sys.exit(app.exec_())
